config-version: 2

name: "jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.8.0b2"
# protobuf incompatibility fix: https://github.com/dbt-labs/dbt-core/releases/tag/v1.8.0b2

profile: jaffle-shop-postgres # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  jaffle_shop:
    +schema: raw

models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
