version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "0.0.0.0:5432:5432"  # Map all IP addresses to container port 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
    # Map the external port 8888 to container port 80
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  dbt:
    container_name: dbt
    build: .
    image: dbt-jaffle-shop
    volumes:
    # Map the current folder in host to /usr/src/dbt in container
      - ./:/usr/src/dbt
    depends_on:
      postgres:
        condition: service_healthy